version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5433:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_SOURCE=postgresql://root:secret@db:5432/simple_bank?sslmode=disable
    ports:
      - "8080:8080"
    command: ["/app/main"]
  

volumes:
  data-volume:
